{
  "formatVersion": "1.1",
  "component": {
    "group": "com.akashi.javassist",
    "module": "modify",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 2314,
          "sha512": "26f71324f9323c16fa5ec40f898a5a8dca3c2d05b82b4661982bd88e34e5914dac20bd9daf14eb376f286097af0da5e3866b621f7e33dd8428f8d9985b7d7215",
          "sha256": "ec7b172b435fb3d8046f4fe5d4bb9d57ddf391868d9e194df432acb134ebd151",
          "sha1": "4114bfc1d3a631b7e0f5dc38e2284f001588502c",
          "md5": "5ff7ba97716b6dd1d697fd02948814c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 2314,
          "sha512": "26f71324f9323c16fa5ec40f898a5a8dca3c2d05b82b4661982bd88e34e5914dac20bd9daf14eb376f286097af0da5e3866b621f7e33dd8428f8d9985b7d7215",
          "sha256": "ec7b172b435fb3d8046f4fe5d4bb9d57ddf391868d9e194df432acb134ebd151",
          "sha1": "4114bfc1d3a631b7e0f5dc38e2284f001588502c",
          "md5": "5ff7ba97716b6dd1d697fd02948814c9"
        }
      ]
    }
  ]
}
