{
  "formatVersion": "1.1",
  "component": {
    "group": "com.akashi.javassist",
    "module": "modify",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 3408,
          "sha512": "2225093e2c3e9a627c8d88bf7c26c0fde63783376b4b6b583347b1be4eddf62efaf14cc1e219057aa599a29a976d5cf5890c9f34fea990bbbbd7fef7d83d6282",
          "sha256": "ab089de23e179c731ceda4ec71f5701126024bb6c73c3c251d6b3b8b6b8e72a3",
          "sha1": "fc41a90074b001ce45c4a14763220db1b9d2ad59",
          "md5": "d2f477fa8515bc672c3059218b9a66ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 3408,
          "sha512": "2225093e2c3e9a627c8d88bf7c26c0fde63783376b4b6b583347b1be4eddf62efaf14cc1e219057aa599a29a976d5cf5890c9f34fea990bbbbd7fef7d83d6282",
          "sha256": "ab089de23e179c731ceda4ec71f5701126024bb6c73c3c251d6b3b8b6b8e72a3",
          "sha1": "fc41a90074b001ce45c4a14763220db1b9d2ad59",
          "md5": "d2f477fa8515bc672c3059218b9a66ca"
        }
      ]
    }
  ]
}
