{
  "formatVersion": "1.1",
  "component": {
    "group": "com.akashi.javassist",
    "module": "modify",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 6339,
          "sha512": "c42f606eba25cf71a5b5a8a757f69a509bb4279f0632eaf0d07d9c1e1b77ee05c0fd8e4091275ac450fba6ecef8f1ea67e4a099bbba54519a5bf16905d62aad8",
          "sha256": "6d4006f6a99adfd00e0e7a093be0c94b87ad933869d081340e20a58b39b2e3d7",
          "sha1": "68a9a7db7fa2036387f5d853c78b72eba0dcc7b1",
          "md5": "b5ab21caabb80b9172b51f6eb59e245f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 6339,
          "sha512": "c42f606eba25cf71a5b5a8a757f69a509bb4279f0632eaf0d07d9c1e1b77ee05c0fd8e4091275ac450fba6ecef8f1ea67e4a099bbba54519a5bf16905d62aad8",
          "sha256": "6d4006f6a99adfd00e0e7a093be0c94b87ad933869d081340e20a58b39b2e3d7",
          "sha1": "68a9a7db7fa2036387f5d853c78b72eba0dcc7b1",
          "md5": "b5ab21caabb80b9172b51f6eb59e245f"
        }
      ]
    }
  ]
}
